require 'fixy/decorator/debug'
require 'fixy/decorator/default'
require 'fixy/document'
require 'fixy/formatter/alphanumeric'
require 'fixy/formatter/amount'
require 'fixy/formatter/ascii'
require 'fixy/formatter/numeric'
require 'fixy/formatter/rate'
require 'fixy/formatter/sign'
require 'fixy/formatter/signed_amount'
require 'fixy/formatter/upcase_alphanumeric'
require 'fixy/formatter/upcase_ascii'
require 'fixy/record'
require 'fixy/version'
require 'i18n'

I18n.load_path << File.expand_path('../fixy/locale/en.yml', __FILE__)