require 'fixy/decorator/debug'
require 'fixy/decorator/default'
require 'fixy/document'
require 'fixy/formatter/alphanumeric'
require 'fixy/formatter/literal'
require 'fixy/record'
require 'fixy/version'
